version: '3.8'

services:
  java_app:
    container_name: commercial.sales
    image: java-app:1.0.0
    build:
      context: ./commercial.sales
      dockerfile: dockerfile
    ports:
      - ${PORT}:8080
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - db
      - db_replica